version: '2'

services:
  renew:
    build: .
    image: artifacts.dsmaher.com/certbot:latest
    container_name: certbot-renew
    volumes:
      - /mnt/nginx/letsencrypt:/etc/letsencrypt
      - /mnt/nginx/nginx/html/.well-known:/usr/share/nginx/html/.well-known
      - /mnt/nginx/log:/var/log/letsencrypt
    environment:
      - WEBROOT=/usr/share/nginx/html
      - EMAIL=dan@dsmaher.com
      - DOMAINS=${DOMAINS}
      - CONCAT=false
      - SEPARATE=${SEPARATE}
    command: sh /scripts/run_renew.sh
  certonly:
    build: .
    image: artifacts.dsmaher.com/certbot:latest
    container_name: certbot-new
    volumes:
      - /mnt/nginx/letsencrypt:/etc/letsencrypt
      - /mnt/nginx/nginx/html/.well-known:/usr/share/nginx/html/.well-known
    environment:
      - WEBROOT=/usr/share/nginx/html
      - EMAIL=dan@dsmaher.com
      - DOMAINS=${DOMAINS}
      - CONCAT=false
      - SEPARATE=${SEPARATE}
    command: sh /scripts/run_certbot.sh

